# AndroidX support 
android.useAndroidX=true
# R library (R.kt/R.java generation).
android.nonTransitiveRClass=true
# Kotlin style, using official. 
kotlin.code.style=official
# Enable parallel execution to build modules at the same time - bruh can increase Ram consumption, remove if issue presits. 
# org.gradle.parallel=true

# all credits goes to gradle.org

# This file is for gradle properties only, using unknown flags can cause build failure - corrupted builds. You've been warned! -@IQ_HARRY_07