# AndroidX support 
android.useAndroidX=true
# R library (R.kt/R.java generation).
android.nonTransitiveRClass=true
# Kotlin style, using official. 
kotlin.code.style=official

# Enable parallel execution to build modules at the same time - bruh can increase Ram consumption, remove if issue presits. 
# org.gradle.parallel=true

# I'm building with Android device, so I have to be careful with ram consumption, change/remove this flag to let Gradle automatically decide the ram consumption (How much ram Gradle should use? :)

# 1GB Ram
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m

# how much ram Kotlin daemon can use?: 
# 1GB Ram
kotlin.daemon.jvmopts=-Xmx1024m


# all credits goes to gradle.org

# This file is for gradle properties only, using unknown flags can cause build failure - corrupted builds. You've been warned! -@IQ_HARRY_07